### ISSUE TITLE
[Feature Request]: Want redesign Ui and Functionalities of ToDo List

### ISSUE THREAD

**Issue by nishant0708** [apu52/METAVERSE#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to redesign and change functionalty of this toDo list.
there are Many things in todoList which we dont Need i want to fix that

### Use Case

![image](https://github.com/user-attachments/assets/06fc4ab2-f992-4073-b03b-7323f9a6dd24)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository
