### ISSUE TITLE
[Bug]: Empty Tasks in To-Do List Project

### ISSUE THREAD

**Issue by abckhush** [apu52/METAVERSE#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

You can add empty tasks to the To-Do List Project. Validation checks are missing

### Expected behavior

Empty tasks should not be there.

### Add ScreenShots

![image](https://github.com/apu52/METAVERSE/assets/127378920/9c8fbddd-4b62-4f27-8bd9-15d25d9abf93)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@abckhush good work

**Comment by abckhush** [comment]
Thankyou! Could you add the level also pls?
