### ISSUE TITLE
[Enhancement of Project]:  Features Missing in To-Do List Project

### ISSUE THREAD

**Issue by abckhush** [apu52/METAVERSE#844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

In To-Do List Project, features are mentioned but are not implemented. I would like to implement the features mentioned.

### Suggested Change

I would like to introduce the features:
1. Priority Levels
2. Add reminders

### Rationale

The features are important as they are mentioned in the project. user expects the project to be able to do what the documentation says. Hence, it is necessary and would also enhance the overall project.
![image](https://github.com/apu52/METAVERSE/assets/127378920/628fc8c9-950a-49bd-9433-468ca63948ac)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@abckhush u are also assigned this issue .but just want to suggest u to submit different PR's respective of different issues

**Comment by abckhush** [comment]
Sure! Could you pls add the level also?

**Comment by apu52** [comment]
> Sure! Could you pls add the level also?

I will add the required label after the review of the PR. Don't worry . It's my responsibility

**Comment by abckhush** [comment]
Ok!
